### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by NaturalHarmonia** [KunoichiZ/SoVJP-NTR-Plugin#4]
I was using cheats with this on Fire Emblem Echoes: Shadows of Valentia and got a FATAL ERROR.

PID: 0x00040030_00008F02
REV: 61806
AID: 0xFFFFFFFF_FFFFFFFF
ADR: 0x00230C34
RSL: 0xD8C3FBF3
Level: -5
Summary: 6
Module: 254
Desc: 1011

The .cia used was BootNTRSelector-FONZD-Banner.cia

I had my system closed for a while and then came back and starting turning cheats on and off.

**Comment by KunoichiZ** [comment]
I've never seen that error before. I don't know how to help with this. Other than you probaly shouldn't do that, try a different version of BootNTR Selector (the other banner) and make sure you have 2.7.3 (the latest at time of writing this) and redownload the plugin.

Other than this, I cannot physically help you because I've never experienced any errors (aside from the few freezes) with the plugin.
